#############################################################################
# Makefile for building: chat.app/Contents/MacOS/chat
# Generated by qmake (3.0) (Qt 5.4.1)
# Project:  chatclient.pro
# Template: app
# Command: /Users/ant0nisktz/Qt5.4.1/5.4/clang_64/bin/qmake -o Makefile chatclient.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I. -Iinclude -I../../../Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I../../../Qt5.4.1/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers -I../../../Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../Qt5.4.1/5.4/clang_64/mkspecs/macx-clang -F/Users/ant0nisktz/Qt5.4.1/5.4/clang_64/lib
QMAKE         = /Users/ant0nisktz/Qt5.4.1/5.4/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = chat1.0.0
DISTDIR = /Users/ant0nisktz/Desktop/Project/ad-hoc-chat/.tmp/chat1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/Users/ant0nisktz/Qt5.4.1/5.4/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/ant0nisktz/Qt5.4.1/5.4/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/chatwindow.cpp \
		src/adhoc.cpp moc_chatwindow.cpp
OBJECTS       = main.o \
		chatwindow.o \
		adhoc.o \
		moc_chatwindow.o
DIST          = ../../../Qt5.4.1/5.4/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/qdevice.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/device_config.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/common/shell-unix.conf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/common/unix.conf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/common/mac.conf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/common/macx.conf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/common/clang.conf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/qconfig.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/spec_post.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/default_post.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/qt.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/resources.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/moc.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/uic.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/yacc.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/lex.prf \
		chatclient.pro include/chatwindow.h \
		include/adhoc.h src/main.cpp \
		src/chatwindow.cpp \
		src/adhoc.cpp
QMAKE_TARGET  = chat
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = chat.app/Contents/MacOS/chat

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d chat.app/Contents/MacOS/ || mkdir -p chat.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	cp -f /Users/ant0nisktz/Desktop/Project/ad-hoc-chat/adhoc_scripts/adhoc_desetup /Users/ant0nisktz/Desktop/Project/ad-hoc-chat//adhoc_desetup

Makefile: chatclient.pro ../../../Qt5.4.1/5.4/clang_64/mkspecs/macx-clang/qmake.conf ../../../Qt5.4.1/5.4/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/qdevice.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/device_config.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/common/shell-unix.conf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/common/unix.conf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/common/mac.conf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/common/macx.conf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/common/clang.conf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/qconfig.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/spec_post.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/default_post.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/qt.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/resources.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/moc.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/uic.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/yacc.prf \
		../../../Qt5.4.1/5.4/clang_64/mkspecs/features/lex.prf \
		chatclient.pro \
		/Users/ant0nisktz/Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/ant0nisktz/Qt5.4.1/5.4/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/ant0nisktz/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile chatclient.pro
../../../Qt5.4.1/5.4/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt5.4.1/5.4/clang_64/mkspecs/qdevice.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/features/device_config.prf:
../../../Qt5.4.1/5.4/clang_64/mkspecs/common/shell-unix.conf:
../../../Qt5.4.1/5.4/clang_64/mkspecs/common/unix.conf:
../../../Qt5.4.1/5.4/clang_64/mkspecs/common/mac.conf:
../../../Qt5.4.1/5.4/clang_64/mkspecs/common/macx.conf:
../../../Qt5.4.1/5.4/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt5.4.1/5.4/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt5.4.1/5.4/clang_64/mkspecs/common/clang.conf:
../../../Qt5.4.1/5.4/clang_64/mkspecs/common/clang-mac.conf:
../../../Qt5.4.1/5.4/clang_64/mkspecs/qconfig.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt5.4.1/5.4/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt5.4.1/5.4/clang_64/mkspecs/features/qt_config.prf:
../../../Qt5.4.1/5.4/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Qt5.4.1/5.4/clang_64/mkspecs/features/spec_post.prf:
../../../Qt5.4.1/5.4/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt5.4.1/5.4/clang_64/mkspecs/features/default_pre.prf:
../../../Qt5.4.1/5.4/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Qt5.4.1/5.4/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt5.4.1/5.4/clang_64/mkspecs/features/default_post.prf:
../../../Qt5.4.1/5.4/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt5.4.1/5.4/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt5.4.1/5.4/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt5.4.1/5.4/clang_64/mkspecs/features/warn_on.prf:
../../../Qt5.4.1/5.4/clang_64/mkspecs/features/qt.prf:
../../../Qt5.4.1/5.4/clang_64/mkspecs/features/resources.prf:
../../../Qt5.4.1/5.4/clang_64/mkspecs/features/moc.prf:
../../../Qt5.4.1/5.4/clang_64/mkspecs/features/unix/opengl.prf:
../../../Qt5.4.1/5.4/clang_64/mkspecs/features/uic.prf:
../../../Qt5.4.1/5.4/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt5.4.1/5.4/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt5.4.1/5.4/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt5.4.1/5.4/clang_64/mkspecs/features/exceptions.prf:
../../../Qt5.4.1/5.4/clang_64/mkspecs/features/yacc.prf:
../../../Qt5.4.1/5.4/clang_64/mkspecs/features/lex.prf:
chatclient.pro:
/Users/ant0nisktz/Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/ant0nisktz/Qt5.4.1/5.4/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/ant0nisktz/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile chatclient.pro

qmake_all: FORCE

chat.app/Contents/PkgInfo: 
	@test -d chat.app/Contents || mkdir -p chat.app/Contents
	@$(DEL_FILE) chat.app/Contents/PkgInfo
	@echo "APPL????" >chat.app/Contents/PkgInfo
chat.app/Contents/Resources/empty.lproj: 
	@test -d chat.app/Contents/Resources || mkdir -p chat.app/Contents/Resources
	@touch chat.app/Contents/Resources/empty.lproj
	
chat.app/Contents/Info.plist: 
	@test -d chat.app/Contents || mkdir -p chat.app/Contents
	@$(DEL_FILE) chat.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.ant0nisk.chat,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,chat,g" -e "s,@TYPEINFO@,????,g" ../../../Qt5.4.1/5.4/clang_64/mkspecs/macx-clang/Info.plist.app >chat.app/Contents/Info.plist

all: Makefile \
		chat.app/Contents/PkgInfo \
		chat.app/Contents/Resources/empty.lproj \
		chat.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents include/chatwindow.h include/adhoc.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/chatwindow.cpp src/adhoc.cpp $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r chat.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_chatwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_chatwindow.cpp
moc_chatwindow.cpp: ../../../Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		include/chatwindow.h
	/Users/ant0nisktz/Qt5.4.1/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/ant0nisktz/Qt5.4.1/5.4/clang_64/mkspecs/macx-clang -I/Users/ant0nisktz/Desktop/Project/ad-hoc-chat -I/Users/ant0nisktz/Desktop/Project/ad-hoc-chat/include -I/Users/ant0nisktz/Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Headers -I/Users/ant0nisktz/Qt5.4.1/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/ant0nisktz/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/ant0nisktz/Qt5.4.1/5.4/clang_64/lib include/chatwindow.h -o moc_chatwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: src/main.cpp include/chatwindow.h \
		../../../Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		include/adhoc.h \
		../../../Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		../../../Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

chatwindow.o: src/chatwindow.cpp include/chatwindow.h \
		../../../Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../../Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTabWidget \
		../../../Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtabwidget.h \
		../../../Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGridLayout \
		../../../Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgridlayout.h \
		../../../Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLineEdit \
		../../../Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlineedit.h \
		../../../Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPushButton \
		../../../Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		../../../Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QVBoxLayout \
		../../../Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		../../../Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		../../../Qt5.4.1/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chatwindow.o src/chatwindow.cpp

adhoc.o: src/adhoc.cpp include/adhoc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o adhoc.o src/adhoc.cpp

moc_chatwindow.o: moc_chatwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_chatwindow.o moc_chatwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

