// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

#ifndef PROTOBUF_Message_2eproto__INCLUDED
#define PROTOBUF_Message_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace MessageProto {
class Message;
class MessageDefaultTypeInternal;
extern MessageDefaultTypeInternal _Message_default_instance_;
}  // namespace MessageProto

namespace MessageProto {

namespace protobuf_Message_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_Message_2eproto

enum Message_Flags {
  Message_Flags_CONNECTED = 0,
  Message_Flags_LEADER = 1,
  Message_Flags_VOTE = 2,
  Message_Flags_CANDIDATE = 3
};
bool Message_Flags_IsValid(int value);
const Message_Flags Message_Flags_Flags_MIN = Message_Flags_CONNECTED;
const Message_Flags Message_Flags_Flags_MAX = Message_Flags_CANDIDATE;
const int Message_Flags_Flags_ARRAYSIZE = Message_Flags_Flags_MAX + 1;

const ::google::protobuf::EnumDescriptor* Message_Flags_descriptor();
inline const ::std::string& Message_Flags_Name(Message_Flags value) {
  return ::google::protobuf::internal::NameOfEnum(
    Message_Flags_descriptor(), value);
}
inline bool Message_Flags_Parse(
    const ::std::string& name, Message_Flags* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Message_Flags>(
    Message_Flags_descriptor(), name, value);
}
// ===================================================================

class Message : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MessageProto.Message) */ {
 public:
  Message();
  virtual ~Message();

  Message(const Message& from);

  inline Message& operator=(const Message& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Message& default_instance();

  static inline const Message* internal_default_instance() {
    return reinterpret_cast<const Message*>(
               &_Message_default_instance_);
  }

  void Swap(Message* other);

  // implements Message ----------------------------------------------

  inline Message* New() const PROTOBUF_FINAL { return New(NULL); }

  Message* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Message& from);
  void MergeFrom(const Message& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Message* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef Message_Flags Flags;
  static const Flags CONNECTED =
    Message_Flags_CONNECTED;
  static const Flags LEADER =
    Message_Flags_LEADER;
  static const Flags VOTE =
    Message_Flags_VOTE;
  static const Flags CANDIDATE =
    Message_Flags_CANDIDATE;
  static inline bool Flags_IsValid(int value) {
    return Message_Flags_IsValid(value);
  }
  static const Flags Flags_MIN =
    Message_Flags_Flags_MIN;
  static const Flags Flags_MAX =
    Message_Flags_Flags_MAX;
  static const int Flags_ARRAYSIZE =
    Message_Flags_Flags_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Flags_descriptor() {
    return Message_Flags_descriptor();
  }
  static inline const ::std::string& Flags_Name(Flags value) {
    return Message_Flags_Name(value);
  }
  static inline bool Flags_Parse(const ::std::string& name,
      Flags* value) {
    return Message_Flags_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // repeated .MessageProto.Message.Flags flags = 4;
  int flags_size() const;
  void clear_flags();
  static const int kFlagsFieldNumber = 4;
  ::MessageProto::Message_Flags flags(int index) const;
  void set_flags(int index, ::MessageProto::Message_Flags value);
  void add_flags(::MessageProto::Message_Flags value);
  const ::google::protobuf::RepeatedField<int>& flags() const;
  ::google::protobuf::RepeatedField<int>* mutable_flags();

  // optional string sender_id = 3;
  bool has_sender_id() const;
  void clear_sender_id();
  static const int kSenderIdFieldNumber = 3;
  const ::std::string& sender_id() const;
  void set_sender_id(const ::std::string& value);
  #if LANG_CXX11
  void set_sender_id(::std::string&& value);
  #endif
  void set_sender_id(const char* value);
  void set_sender_id(const char* value, size_t size);
  ::std::string* mutable_sender_id();
  ::std::string* release_sender_id();
  void set_allocated_sender_id(::std::string* sender_id);

  // optional string checksum = 16;
  bool has_checksum() const;
  void clear_checksum();
  static const int kChecksumFieldNumber = 16;
  const ::std::string& checksum() const;
  void set_checksum(const ::std::string& value);
  #if LANG_CXX11
  void set_checksum(::std::string&& value);
  #endif
  void set_checksum(const char* value);
  void set_checksum(const char* value, size_t size);
  ::std::string* mutable_checksum();
  ::std::string* release_checksum();
  void set_allocated_checksum(::std::string* checksum);

  // optional string payload = 17;
  bool has_payload() const;
  void clear_payload();
  static const int kPayloadFieldNumber = 17;
  const ::std::string& payload() const;
  void set_payload(const ::std::string& value);
  #if LANG_CXX11
  void set_payload(::std::string&& value);
  #endif
  void set_payload(const char* value);
  void set_payload(const char* value, size_t size);
  ::std::string* mutable_payload();
  ::std::string* release_payload();
  void set_allocated_payload(::std::string* payload);

  // optional int32 seq = 1;
  bool has_seq() const;
  void clear_seq();
  static const int kSeqFieldNumber = 1;
  ::google::protobuf::int32 seq() const;
  void set_seq(::google::protobuf::int32 value);

  // optional int32 msg_id = 2;
  bool has_msg_id() const;
  void clear_msg_id();
  static const int kMsgIdFieldNumber = 2;
  ::google::protobuf::int32 msg_id() const;
  void set_msg_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:MessageProto.Message)
 private:
  void set_has_seq();
  void clear_has_seq();
  void set_has_msg_id();
  void clear_has_msg_id();
  void set_has_sender_id();
  void clear_has_sender_id();
  void set_has_checksum();
  void clear_has_checksum();
  void set_has_payload();
  void clear_has_payload();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField<int> flags_;
  ::google::protobuf::internal::ArenaStringPtr sender_id_;
  ::google::protobuf::internal::ArenaStringPtr checksum_;
  ::google::protobuf::internal::ArenaStringPtr payload_;
  ::google::protobuf::int32 seq_;
  ::google::protobuf::int32 msg_id_;
  friend struct protobuf_Message_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Message

// optional int32 seq = 1;
inline bool Message::has_seq() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Message::set_has_seq() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Message::clear_has_seq() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Message::clear_seq() {
  seq_ = 0;
  clear_has_seq();
}
inline ::google::protobuf::int32 Message::seq() const {
  // @@protoc_insertion_point(field_get:MessageProto.Message.seq)
  return seq_;
}
inline void Message::set_seq(::google::protobuf::int32 value) {
  set_has_seq();
  seq_ = value;
  // @@protoc_insertion_point(field_set:MessageProto.Message.seq)
}

// optional int32 msg_id = 2;
inline bool Message::has_msg_id() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Message::set_has_msg_id() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Message::clear_has_msg_id() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Message::clear_msg_id() {
  msg_id_ = 0;
  clear_has_msg_id();
}
inline ::google::protobuf::int32 Message::msg_id() const {
  // @@protoc_insertion_point(field_get:MessageProto.Message.msg_id)
  return msg_id_;
}
inline void Message::set_msg_id(::google::protobuf::int32 value) {
  set_has_msg_id();
  msg_id_ = value;
  // @@protoc_insertion_point(field_set:MessageProto.Message.msg_id)
}

// optional string sender_id = 3;
inline bool Message::has_sender_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Message::set_has_sender_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Message::clear_has_sender_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Message::clear_sender_id() {
  sender_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_sender_id();
}
inline const ::std::string& Message::sender_id() const {
  // @@protoc_insertion_point(field_get:MessageProto.Message.sender_id)
  return sender_id_.GetNoArena();
}
inline void Message::set_sender_id(const ::std::string& value) {
  set_has_sender_id();
  sender_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MessageProto.Message.sender_id)
}
#if LANG_CXX11
inline void Message::set_sender_id(::std::string&& value) {
  set_has_sender_id();
  sender_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:MessageProto.Message.sender_id)
}
#endif
inline void Message::set_sender_id(const char* value) {
  set_has_sender_id();
  sender_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MessageProto.Message.sender_id)
}
inline void Message::set_sender_id(const char* value, size_t size) {
  set_has_sender_id();
  sender_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MessageProto.Message.sender_id)
}
inline ::std::string* Message::mutable_sender_id() {
  set_has_sender_id();
  // @@protoc_insertion_point(field_mutable:MessageProto.Message.sender_id)
  return sender_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Message::release_sender_id() {
  // @@protoc_insertion_point(field_release:MessageProto.Message.sender_id)
  clear_has_sender_id();
  return sender_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Message::set_allocated_sender_id(::std::string* sender_id) {
  if (sender_id != NULL) {
    set_has_sender_id();
  } else {
    clear_has_sender_id();
  }
  sender_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), sender_id);
  // @@protoc_insertion_point(field_set_allocated:MessageProto.Message.sender_id)
}

// repeated .MessageProto.Message.Flags flags = 4;
inline int Message::flags_size() const {
  return flags_.size();
}
inline void Message::clear_flags() {
  flags_.Clear();
}
inline ::MessageProto::Message_Flags Message::flags(int index) const {
  // @@protoc_insertion_point(field_get:MessageProto.Message.flags)
  return static_cast< ::MessageProto::Message_Flags >(flags_.Get(index));
}
inline void Message::set_flags(int index, ::MessageProto::Message_Flags value) {
  assert(::MessageProto::Message_Flags_IsValid(value));
  flags_.Set(index, value);
  // @@protoc_insertion_point(field_set:MessageProto.Message.flags)
}
inline void Message::add_flags(::MessageProto::Message_Flags value) {
  assert(::MessageProto::Message_Flags_IsValid(value));
  flags_.Add(value);
  // @@protoc_insertion_point(field_add:MessageProto.Message.flags)
}
inline const ::google::protobuf::RepeatedField<int>&
Message::flags() const {
  // @@protoc_insertion_point(field_list:MessageProto.Message.flags)
  return flags_;
}
inline ::google::protobuf::RepeatedField<int>*
Message::mutable_flags() {
  // @@protoc_insertion_point(field_mutable_list:MessageProto.Message.flags)
  return &flags_;
}

// optional string checksum = 16;
inline bool Message::has_checksum() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Message::set_has_checksum() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Message::clear_has_checksum() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Message::clear_checksum() {
  checksum_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_checksum();
}
inline const ::std::string& Message::checksum() const {
  // @@protoc_insertion_point(field_get:MessageProto.Message.checksum)
  return checksum_.GetNoArena();
}
inline void Message::set_checksum(const ::std::string& value) {
  set_has_checksum();
  checksum_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MessageProto.Message.checksum)
}
#if LANG_CXX11
inline void Message::set_checksum(::std::string&& value) {
  set_has_checksum();
  checksum_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:MessageProto.Message.checksum)
}
#endif
inline void Message::set_checksum(const char* value) {
  set_has_checksum();
  checksum_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MessageProto.Message.checksum)
}
inline void Message::set_checksum(const char* value, size_t size) {
  set_has_checksum();
  checksum_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MessageProto.Message.checksum)
}
inline ::std::string* Message::mutable_checksum() {
  set_has_checksum();
  // @@protoc_insertion_point(field_mutable:MessageProto.Message.checksum)
  return checksum_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Message::release_checksum() {
  // @@protoc_insertion_point(field_release:MessageProto.Message.checksum)
  clear_has_checksum();
  return checksum_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Message::set_allocated_checksum(::std::string* checksum) {
  if (checksum != NULL) {
    set_has_checksum();
  } else {
    clear_has_checksum();
  }
  checksum_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), checksum);
  // @@protoc_insertion_point(field_set_allocated:MessageProto.Message.checksum)
}

// optional string payload = 17;
inline bool Message::has_payload() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Message::set_has_payload() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Message::clear_has_payload() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Message::clear_payload() {
  payload_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_payload();
}
inline const ::std::string& Message::payload() const {
  // @@protoc_insertion_point(field_get:MessageProto.Message.payload)
  return payload_.GetNoArena();
}
inline void Message::set_payload(const ::std::string& value) {
  set_has_payload();
  payload_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MessageProto.Message.payload)
}
#if LANG_CXX11
inline void Message::set_payload(::std::string&& value) {
  set_has_payload();
  payload_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:MessageProto.Message.payload)
}
#endif
inline void Message::set_payload(const char* value) {
  set_has_payload();
  payload_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MessageProto.Message.payload)
}
inline void Message::set_payload(const char* value, size_t size) {
  set_has_payload();
  payload_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MessageProto.Message.payload)
}
inline ::std::string* Message::mutable_payload() {
  set_has_payload();
  // @@protoc_insertion_point(field_mutable:MessageProto.Message.payload)
  return payload_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Message::release_payload() {
  // @@protoc_insertion_point(field_release:MessageProto.Message.payload)
  clear_has_payload();
  return payload_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Message::set_allocated_payload(::std::string* payload) {
  if (payload != NULL) {
    set_has_payload();
  } else {
    clear_has_payload();
  }
  payload_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), payload);
  // @@protoc_insertion_point(field_set_allocated:MessageProto.Message.payload)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace MessageProto

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::MessageProto::Message_Flags> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::MessageProto::Message_Flags>() {
  return ::MessageProto::Message_Flags_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Message_2eproto__INCLUDED
